spring:
  application:
    name: sbauth0client
    
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-d220wagjrgvyxprf.us.auth0.com/
          audiences: https://userapi         

      client:
        registration:
          auth0:
            client-id: TM7ZF2TTGrP6TFKJBeZsXXqGmuYVSpqi
            client-secret: B1HH6DJ8eCn2dH7OG6BrAHzCtn_g1yxcL3nVB7xerYLDFR8OQhrD2qK8P0hgEnhm
        provider:
          auth0:
            token-uri: https://dev-d220wagjrgvyxprf.us.auth0.com/oauth/token     
            
logging:
  level:
    org:
      springframework:
        security: DEBUG
            
            
            
          
            
            
            




        
                     